import assert from "node:assert/strict";
import { completeSupportRound, parseSupportRecord, safeCheckoutUrl, SUPPORT_COOLDOWN_MS } from "../app/lib/supportPrompt";
import { buildRoundSchedule, ServerClock, scheduleChanged } from "../app/lib/serverClock";
const now = 1700000000000;
let record = parseSupportRecord(null, now);
const result = completeSupportRound(record, "round1", now);
assert.equal(result.eligible, true);
record = { ...result.record, lastShown: now };
assert.equal(completeSupportRound(record, "round1", now + SUPPORT_COOLDOWN_MS).eligible, false);
assert.equal(completeSupportRound(record, "round2", now + SUPPORT_COOLDOWN_MS - 1).eligible, false);
assert.equal(completeSupportRound(record, "round3", now + SUPPORT_COOLDOWN_MS).eligible, true);
assert.equal(parseSupportRecord(JSON.stringify({ lastShown: now + 1 }), now).lastShown, 0);
assert.deepEqual(parseSupportRecord("invalid"), { count: 0, completed: [], lastShown: 0 });
for (const url of ["javascript:alert(1)", "https://checkout.dodopayments.com.evil.com/session/x", "http://checkout.dodopayments.com", "https://evil@checkout.dodopayments.com", "https://checkout.dodopayments.com:444/"]) assert.equal(safeCheckoutUrl(url), null);
assert.ok(safeCheckoutUrl("https://checkout.dodopayments.com/session/cks_x"));
assert.ok(safeCheckoutUrl("https://test.checkout.dodopayments.com/session/cks_x"));
const clock = new ServerClock();
const playing = buildRoundSchedule({ protocolVersion: 2, serverPhase: "playing", generation: 2, duration: 10, countdownSec: 1, serverTime: now, scanStartsAt: now, countdownEndsAt: now }, clock, "round", now, now);
const paused = { ...playing, serverPhase: "paused", generation: 3, remainingMs: 6400 };
assert.ok(scheduleChanged(playing, paused));
const resumed = buildRoundSchedule({ protocolVersion: 2, serverPhase: "playing", generation: 4, duration: 6.4, serverTime: now + 8000 }, clock, "round", now + 8000, now + 8000);
assert.equal(resumed.scanEndsAt - resumed.scanStartsAt, 6400);
console.log("Support cooldown, duplicate completion, checkout URL and paused/resumed schedule checks passed.");
